steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/portfolio-matxa/contime:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/portfolio-matxa/contime:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'portfolio-matxa', '--region=us-central1', '--platform=managed', '--image=gcr.io/portfolio-matxa/contime:$SHORT_SHA']
